# Generated by Django 3.0 on 2022-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='nome_completo',
            field=models.CharField(max_length=194, verbose_name='Nome Completo'),
        ),
    ]
