# Generated by Django 3.0 on 2022-01-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
        ('gestores', '0002_auto_20220107_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='cargo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cargos.Cargo', verbose_name='Cargo'),
        ),
    ]
