# Generated by Django 3.0 on 2022-01-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestores', '0003_auto_20220107_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='nivel_report',
        ),
    ]
